version: '3'
services:
  anime-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3003:3000"
    container_name: anime-app
    stdin_open: true
    volumes:
       - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb

  
  mongodb:
    image: "mongo"
    container_name: mongodb
    volumes:
      - data:/data/db
      - ./Database/anime-app:/backup/anime-app
    env_file:
      - mongo.env
    # environment:
    #   - MONGODB_USERNAME=yahya
    #   - MONGODB_PASSWORD=25020680
    ports:
      - 28017:27017
  

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=yahya
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=25020680        
      - ME_CONFIG_MONGODB_URL=mongodb://yahya:25020680@mongodb:27017
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"

volumes:
  data: