version: '3'
services:
  anime-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    container_name: anime-app
    stdin_open: true
    volumes:
       - .:/app
    env_file:
      - .env