HUGGINGFACE_TOKEN = "api_muCLbvAyTrOEQEuBBDmUzbHnNfRtREvCBj";
DISCORD_RYUK_TOKEN =
  "ODgxNjY5MDA3MzQ0Nzk5Nzk1.YSwMPw.HSeYd3C_BtrnMg2EiBPpoDSM6qg";
DISCORD_LIGHT_TOKEN =
  "ODgyMDE2MjAwNTM4ODUzNDA3.YS1PmQ.goMAKJyLx98uz60dXqwFSqdTniI";
DISCORD_L_TOKEN = "ODgzMTE2ODgwMTU4NjgzMTY2.YTFQrw.wuU5Lmom-l0wvV0ggXHovBSObiw";
DISCORD_EREN_TOKEN =
  "ODgzMTM5OTYyOTE5MzQyMTIw.YTFmLw.3mXIL2b8IS3d61mttDJB3jaCFM0";
DISCORD_GINTOKI_TOKEN =
  "ODgzNDAwODM3NDYyODk2Njcx.YTJZJA.bGfZyDLxI89hC9uNgYRmiY07FjM";
DISCORD_MIGI_TOKEN =
  "ODgzNzc2NDM5NjQ2ODE0MjE4.YTO28g.EiuYDdN1hpXyS6gUNcFnU4h-fiE";
DISCORD_REM_TOKEN =
  "ODg1MzE2MDI0NTAzNzg3NTcx.YTlQzA.mJpjLHt1O7vzK-C3QHf-JzkDgh8";
DISCORD_SUBARU_TOKEN =
  "ODg4ODA5NTMzOTIzNzg2ODI0.YUYGYg.0r3SislJInNfGduFx8pjSFXF0SQ";
